version: "3.7"

services:

  nginx:
    build:
      context: .
      args:
        - version=1.16.1
        - build=dev
    image: leadstec/nginx:1.16.1
    init: true
    ports:
      - "50101:80"
    volumes:
      - ~/volumes/nginx.local/log:/data/log
      - ~/volumes/nginx.local/persist:/data/persist
    env_file:
      - ../../env/debug.env
    environment:
      - NGINX_WORKER_PROCESSES=1
      - NGINX_WORKER_CONNECTIONS=512
      - NGINX_CLIENT_MAX_BODY_SIZE=16m
    secrets:
      - lcs
    hostname: nginx.local
    container_name: nginx.local

secrets:
  lcs:
    file: ~/.vcubi/lcs
