version: "3.8"

services:

  nginx:
    build:
      context: .
    image: leadstec/nginx:1.18
    ports:
      - "50101:80"
    volumes:
      - ~/volumes/nginx.local/log:/data/log
      - ~/volumes/nginx.local/persist:/data/persist
    environment:
      - NGINX_WORKER_CONNECTIONS=512
      - NGINX_CLIENT_MAX_BODY_SIZE=16m
    secrets:
      - lcs
    hostname: nginx.local
    container_name: nginx.local
    entrypoint: ["lcsd", "run", "start", "---", "/scripts/debug.sh"]

secrets:
  lcs:
    file: ~/.vcubi/lcs
