#!/bin/bash

set -e

clog -t "nginx: Build process starts ..."

# add image schema
lcs-cli schema add --section nginx

# Add nginx user to ide group
addgroup nginx lcs
clog -i "nginx: User nginx added to LCS group."

# create default html directory
chown -R nginx:lcs ${APP_DIR}
clog -i "nginx: fixed ownership of ${APP_DIR}"

# fix nginx problems pid failed
mkdir -p /run/nginx

# nginx
cp -f /scripts/setup/nginx/nginx.conf /etc/nginx/nginx.conf
cp -f /scripts/setup/nginx/default.conf /etc/nginx/conf.d/default.conf
clog -i "nginx: default configuration templates copied."

# nginx supervisor config
cat > /etc/supervisor.conf.d/nginx.conf <<EOF
[program:nginx]
directory=/
command=/usr/sbin/nginx -c /etc/nginx/nginx.conf
user=root
autostart=true
autorestart=true
stdout_logfile=${LOG_DIR}/supervisor/%(program_name)s.log
stderr_logfile=${LOG_DIR}/supervisor/%(program_name)s.log
EOF
clog -i "nginx: supervisor configuration created."

# Create profile for global env in different shells
cat > /etc/profile.d/nginx.sh <<EOF
export NGINX_LOG_DIR=${NGINX_LOG_DIR}
EOF
clog -i "nginx: Global ENVs added to /etc/profile.d"

# complete
clog -t "nginx: Build process completed."
